// Generated by gencpp from file rasp_test/Canny.msg
// DO NOT EDIT!


#ifndef RASP_TEST_MESSAGE_CANNY_H
#define RASP_TEST_MESSAGE_CANNY_H

#include <ros/service_traits.h>


#include <rasp_test/CannyRequest.h>
#include <rasp_test/CannyResponse.h>


namespace rasp_test
{

struct Canny
{

typedef CannyRequest Request;
typedef CannyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Canny
} // namespace rasp_test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rasp_test::Canny > {
  static const char* value()
  {
    return "5d927b78b5235b8ef943f0f8abea7a79";
  }

  static const char* value(const ::rasp_test::Canny&) { return value(); }
};

template<>
struct DataType< ::rasp_test::Canny > {
  static const char* value()
  {
    return "rasp_test/Canny";
  }

  static const char* value(const ::rasp_test::Canny&) { return value(); }
};


// service_traits::MD5Sum< ::rasp_test::CannyRequest> should match 
// service_traits::MD5Sum< ::rasp_test::Canny > 
template<>
struct MD5Sum< ::rasp_test::CannyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rasp_test::Canny >::value();
  }
  static const char* value(const ::rasp_test::CannyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rasp_test::CannyRequest> should match 
// service_traits::DataType< ::rasp_test::Canny > 
template<>
struct DataType< ::rasp_test::CannyRequest>
{
  static const char* value()
  {
    return DataType< ::rasp_test::Canny >::value();
  }
  static const char* value(const ::rasp_test::CannyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rasp_test::CannyResponse> should match 
// service_traits::MD5Sum< ::rasp_test::Canny > 
template<>
struct MD5Sum< ::rasp_test::CannyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rasp_test::Canny >::value();
  }
  static const char* value(const ::rasp_test::CannyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rasp_test::CannyResponse> should match 
// service_traits::DataType< ::rasp_test::Canny > 
template<>
struct DataType< ::rasp_test::CannyResponse>
{
  static const char* value()
  {
    return DataType< ::rasp_test::Canny >::value();
  }
  static const char* value(const ::rasp_test::CannyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RASP_TEST_MESSAGE_CANNY_H
