// Generated by gencpp from file whiterabbit/CannyRequest.msg
// DO NOT EDIT!


#ifndef WHITERABBIT_MESSAGE_CANNYREQUEST_H
#define WHITERABBIT_MESSAGE_CANNYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace whiterabbit
{
template <class ContainerAllocator>
struct CannyRequest_
{
  typedef CannyRequest_<ContainerAllocator> Type;

  CannyRequest_()
    : origin()  {
    }
  CannyRequest_(const ContainerAllocator& _alloc)
    : origin(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _origin_type;
  _origin_type origin;





  typedef boost::shared_ptr< ::whiterabbit::CannyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::whiterabbit::CannyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CannyRequest_

typedef ::whiterabbit::CannyRequest_<std::allocator<void> > CannyRequest;

typedef boost::shared_ptr< ::whiterabbit::CannyRequest > CannyRequestPtr;
typedef boost::shared_ptr< ::whiterabbit::CannyRequest const> CannyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::whiterabbit::CannyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::whiterabbit::CannyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace whiterabbit

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::whiterabbit::CannyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whiterabbit::CannyRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whiterabbit::CannyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whiterabbit::CannyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whiterabbit::CannyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whiterabbit::CannyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::whiterabbit::CannyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b9e7d1cbbc76d39cb8d5177ea4b8ca5b";
  }

  static const char* value(const ::whiterabbit::CannyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb9e7d1cbbc76d39cULL;
  static const uint64_t static_value2 = 0xb8d5177ea4b8ca5bULL;
};

template<class ContainerAllocator>
struct DataType< ::whiterabbit::CannyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "whiterabbit/CannyRequest";
  }

  static const char* value(const ::whiterabbit::CannyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::whiterabbit::CannyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image origin\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of camera\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::whiterabbit::CannyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::whiterabbit::CannyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.origin);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CannyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::whiterabbit::CannyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::whiterabbit::CannyRequest_<ContainerAllocator>& v)
  {
    s << indent << "origin: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.origin);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHITERABBIT_MESSAGE_CANNYREQUEST_H
